services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: markdownhub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  pgadmin:
    image: dpage/pgadmin4:9
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: Admin123..
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy
  app:
    build: .
    volumes:
      - ./uploads:/uploads:rw
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/markdownhub?sslmode=disable
      ADDR: :8080
    ports:
      - "8080:8080"

volumes:
  pgdata:
  pgadmin_data:
