// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin_logs.sql

package store

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countAdminLogs = `-- name: CountAdminLogs :one
SELECT COUNT(*) FROM admin_logs
`

func (q *Queries) CountAdminLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminLog = `-- name: CreateAdminLog :one
INSERT INTO admin_logs (admin_id, action, target_type, target_id, target_username, details, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, admin_id, action, target_type, target_id, target_username, details, ip_address, user_agent, created_at
`

type CreateAdminLogParams struct {
	AdminID        uuid.UUID             `json:"admin_id"`
	Action         string                `json:"action"`
	TargetType     string                `json:"target_type"`
	TargetID       uuid.NullUUID         `json:"target_id"`
	TargetUsername sql.NullString        `json:"target_username"`
	Details        pqtype.NullRawMessage `json:"details"`
	IpAddress      sql.NullString        `json:"ip_address"`
	UserAgent      sql.NullString        `json:"user_agent"`
}

func (q *Queries) CreateAdminLog(ctx context.Context, arg CreateAdminLogParams) (AdminLog, error) {
	row := q.db.QueryRowContext(ctx, createAdminLog,
		arg.AdminID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.TargetUsername,
		arg.Details,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AdminLog
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.TargetUsername,
		&i.Details,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const listAdminLogs = `-- name: ListAdminLogs :many
SELECT 
  al.id, 
  al.admin_id, 
  u.username as admin_username,
  al.action, 
  al.target_type, 
  al.target_id, 
  al.target_username, 
  al.details, 
  al.ip_address, 
  al.user_agent, 
  al.created_at
FROM admin_logs al
LEFT JOIN users u ON al.admin_id = u.id
ORDER BY al.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAdminLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAdminLogsRow struct {
	ID             uuid.UUID             `json:"id"`
	AdminID        uuid.UUID             `json:"admin_id"`
	AdminUsername  sql.NullString        `json:"admin_username"`
	Action         string                `json:"action"`
	TargetType     string                `json:"target_type"`
	TargetID       uuid.NullUUID         `json:"target_id"`
	TargetUsername sql.NullString        `json:"target_username"`
	Details        pqtype.NullRawMessage `json:"details"`
	IpAddress      sql.NullString        `json:"ip_address"`
	UserAgent      sql.NullString        `json:"user_agent"`
	CreatedAt      time.Time             `json:"created_at"`
}

func (q *Queries) ListAdminLogs(ctx context.Context, arg ListAdminLogsParams) ([]ListAdminLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminLogsRow{}
	for rows.Next() {
		var i ListAdminLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.AdminUsername,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.TargetUsername,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminLogsByAdmin = `-- name: ListAdminLogsByAdmin :many
SELECT 
  al.id, 
  al.admin_id, 
  u.username as admin_username,
  al.action, 
  al.target_type, 
  al.target_id, 
  al.target_username, 
  al.details, 
  al.ip_address, 
  al.user_agent, 
  al.created_at
FROM admin_logs al
LEFT JOIN users u ON al.admin_id = u.id
WHERE al.admin_id = $1
ORDER BY al.created_at DESC
LIMIT $2 OFFSET $3
`

type ListAdminLogsByAdminParams struct {
	AdminID uuid.UUID `json:"admin_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

type ListAdminLogsByAdminRow struct {
	ID             uuid.UUID             `json:"id"`
	AdminID        uuid.UUID             `json:"admin_id"`
	AdminUsername  sql.NullString        `json:"admin_username"`
	Action         string                `json:"action"`
	TargetType     string                `json:"target_type"`
	TargetID       uuid.NullUUID         `json:"target_id"`
	TargetUsername sql.NullString        `json:"target_username"`
	Details        pqtype.NullRawMessage `json:"details"`
	IpAddress      sql.NullString        `json:"ip_address"`
	UserAgent      sql.NullString        `json:"user_agent"`
	CreatedAt      time.Time             `json:"created_at"`
}

func (q *Queries) ListAdminLogsByAdmin(ctx context.Context, arg ListAdminLogsByAdminParams) ([]ListAdminLogsByAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminLogsByAdmin, arg.AdminID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminLogsByAdminRow{}
	for rows.Next() {
		var i ListAdminLogsByAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.AdminUsername,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.TargetUsername,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
