// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ai.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countAIConversationsByUser = `-- name: CountAIConversationsByUser :one
SELECT COUNT(*) FROM ai_conversations WHERE user_id = $1
`

func (q *Queries) CountAIConversationsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAIConversationsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAIConversation = `-- name: CreateAIConversation :one
INSERT INTO ai_conversations (user_id, document_id, title)
VALUES ($1, $2, $3)
RETURNING id, user_id, document_id, title, created_at
`

type CreateAIConversationParams struct {
	UserID     uuid.UUID `json:"user_id"`
	DocumentID uuid.UUID `json:"document_id"`
	Title      string    `json:"title"`
}

func (q *Queries) CreateAIConversation(ctx context.Context, arg CreateAIConversationParams) (AiConversation, error) {
	row := q.db.QueryRowContext(ctx, createAIConversation, arg.UserID, arg.DocumentID, arg.Title)
	var i AiConversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DocumentID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const createAIMessage = `-- name: CreateAIMessage :one
INSERT INTO ai_messages (conversation_id, role, content)
VALUES ($1, $2, $3)
RETURNING id, conversation_id, role, content, created_at
`

type CreateAIMessageParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	Role           string    `json:"role"`
	Content        string    `json:"content"`
}

func (q *Queries) CreateAIMessage(ctx context.Context, arg CreateAIMessageParams) (AiMessage, error) {
	row := q.db.QueryRowContext(ctx, createAIMessage, arg.ConversationID, arg.Role, arg.Content)
	var i AiMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAIConversation = `-- name: DeleteAIConversation :exec
DELETE FROM ai_conversations WHERE id = $1
`

func (q *Queries) DeleteAIConversation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAIConversation, id)
	return err
}

const getAIConversationByID = `-- name: GetAIConversationByID :one
SELECT id, user_id, document_id, title, created_at FROM ai_conversations WHERE id = $1
`

func (q *Queries) GetAIConversationByID(ctx context.Context, id uuid.UUID) (AiConversation, error) {
	row := q.db.QueryRowContext(ctx, getAIConversationByID, id)
	var i AiConversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DocumentID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestAIMessages = `-- name: GetLatestAIMessages :many
SELECT id, conversation_id, role, content, created_at FROM ai_messages
WHERE conversation_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetLatestAIMessagesParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) GetLatestAIMessages(ctx context.Context, arg GetLatestAIMessagesParams) ([]AiMessage, error) {
	rows, err := q.db.QueryContext(ctx, getLatestAIMessages, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiMessage{}
	for rows.Next() {
		var i AiMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIConversationsByDocument = `-- name: ListAIConversationsByDocument :many
SELECT id, user_id, document_id, title, created_at FROM ai_conversations
WHERE document_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAIConversationsByDocumentParams struct {
	DocumentID uuid.UUID `json:"document_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListAIConversationsByDocument(ctx context.Context, arg ListAIConversationsByDocumentParams) ([]AiConversation, error) {
	rows, err := q.db.QueryContext(ctx, listAIConversationsByDocument, arg.DocumentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiConversation{}
	for rows.Next() {
		var i AiConversation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DocumentID,
			&i.Title,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIConversationsByUser = `-- name: ListAIConversationsByUser :many
SELECT id, user_id, document_id, title, created_at FROM ai_conversations
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAIConversationsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListAIConversationsByUser(ctx context.Context, arg ListAIConversationsByUserParams) ([]AiConversation, error) {
	rows, err := q.db.QueryContext(ctx, listAIConversationsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiConversation{}
	for rows.Next() {
		var i AiConversation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DocumentID,
			&i.Title,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIMessagesByConversation = `-- name: ListAIMessagesByConversation :many
SELECT id, conversation_id, role, content, created_at FROM ai_messages
WHERE conversation_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListAIMessagesByConversation(ctx context.Context, conversationID uuid.UUID) ([]AiMessage, error) {
	rows, err := q.db.QueryContext(ctx, listAIMessagesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiMessage{}
	for rows.Next() {
		var i AiMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
