// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: attachments.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countAttachmentsUploaded = `-- name: CountAttachmentsUploaded :one
SELECT COUNT(*) FROM attachments WHERE upload_by = $1
`

func (q *Queries) CountAttachmentsUploaded(ctx context.Context, uploadBy uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAttachmentsUploaded, uploadBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (document_id, upload_by, filename, file_type, file_size, file_path)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, document_id, upload_by, filename, file_type, file_size, file_path, created_at
`

type CreateAttachmentParams struct {
	DocumentID uuid.NullUUID `json:"document_id"`
	UploadBy   uuid.UUID     `json:"upload_by"`
	Filename   string        `json:"filename"`
	FileType   string        `json:"file_type"`
	FileSize   int64         `json:"file_size"`
	FilePath   string        `json:"file_path"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, createAttachment,
		arg.DocumentID,
		arg.UploadBy,
		arg.Filename,
		arg.FileType,
		arg.FileSize,
		arg.FilePath,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.UploadBy,
		&i.Filename,
		&i.FileType,
		&i.FileSize,
		&i.FilePath,
		&i.CreatedAt,
	)
	return i, err
}

const createAttachmentReference = `-- name: CreateAttachmentReference :one
INSERT INTO attachment_references (attachment_id, document_id, referenced_at)
VALUES ($1, $2, $3)
RETURNING id, attachment_id, document_id, referenced_at, created_at
`

type CreateAttachmentReferenceParams struct {
	AttachmentID uuid.UUID `json:"attachment_id"`
	DocumentID   uuid.UUID `json:"document_id"`
	ReferencedAt int32     `json:"referenced_at"`
}

func (q *Queries) CreateAttachmentReference(ctx context.Context, arg CreateAttachmentReferenceParams) (AttachmentReference, error) {
	row := q.db.QueryRowContext(ctx, createAttachmentReference, arg.AttachmentID, arg.DocumentID, arg.ReferencedAt)
	var i AttachmentReference
	err := row.Scan(
		&i.ID,
		&i.AttachmentID,
		&i.DocumentID,
		&i.ReferencedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM attachments WHERE id = $1
`

func (q *Queries) DeleteAttachment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAttachment, id)
	return err
}

const deleteAttachmentReference = `-- name: DeleteAttachmentReference :exec
DELETE FROM attachment_references WHERE attachment_id = $1 AND document_id = $2
`

type DeleteAttachmentReferenceParams struct {
	AttachmentID uuid.UUID `json:"attachment_id"`
	DocumentID   uuid.UUID `json:"document_id"`
}

func (q *Queries) DeleteAttachmentReference(ctx context.Context, arg DeleteAttachmentReferenceParams) error {
	_, err := q.db.ExecContext(ctx, deleteAttachmentReference, arg.AttachmentID, arg.DocumentID)
	return err
}

const getAttachmentByID = `-- name: GetAttachmentByID :one
SELECT id, document_id, upload_by, filename, file_type, file_size, file_path, created_at FROM attachments WHERE id = $1
`

func (q *Queries) GetAttachmentByID(ctx context.Context, id uuid.UUID) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, getAttachmentByID, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.UploadBy,
		&i.Filename,
		&i.FileType,
		&i.FileSize,
		&i.FilePath,
		&i.CreatedAt,
	)
	return i, err
}

const getUnreferencedAttachments = `-- name: GetUnreferencedAttachments :many
SELECT a.id, a.document_id, a.upload_by, a.filename, a.file_type, a.file_size, a.file_path, a.created_at FROM attachments a
LEFT JOIN attachment_references ar ON a.id = ar.attachment_id
WHERE a.document_id = $1 AND ar.id IS NULL
`

func (q *Queries) GetUnreferencedAttachments(ctx context.Context, documentID uuid.NullUUID) ([]Attachment, error) {
	rows, err := q.db.QueryContext(ctx, getUnreferencedAttachments, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.UploadBy,
			&i.Filename,
			&i.FileType,
			&i.FileSize,
			&i.FilePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentReferences = `-- name: ListAttachmentReferences :many
SELECT id, attachment_id, document_id, referenced_at, created_at FROM attachment_references WHERE attachment_id = $1
`

func (q *Queries) ListAttachmentReferences(ctx context.Context, attachmentID uuid.UUID) ([]AttachmentReference, error) {
	rows, err := q.db.QueryContext(ctx, listAttachmentReferences, attachmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttachmentReference{}
	for rows.Next() {
		var i AttachmentReference
		if err := rows.Scan(
			&i.ID,
			&i.AttachmentID,
			&i.DocumentID,
			&i.ReferencedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentAttachmentReferences = `-- name: ListDocumentAttachmentReferences :many
SELECT ar.id, ar.attachment_id, ar.document_id, ar.referenced_at, ar.created_at FROM attachment_references ar
JOIN attachments a ON ar.attachment_id = a.id
WHERE a.document_id = $1
`

func (q *Queries) ListDocumentAttachmentReferences(ctx context.Context, documentID uuid.NullUUID) ([]AttachmentReference, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentAttachmentReferences, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttachmentReference{}
	for rows.Next() {
		var i AttachmentReference
		if err := rows.Scan(
			&i.ID,
			&i.AttachmentID,
			&i.DocumentID,
			&i.ReferencedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentAttachments = `-- name: ListDocumentAttachments :many
SELECT id, document_id, upload_by, filename, file_type, file_size, file_path, created_at FROM attachments WHERE document_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDocumentAttachments(ctx context.Context, documentID uuid.NullUUID) ([]Attachment, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentAttachments, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.UploadBy,
			&i.Filename,
			&i.FileType,
			&i.FileSize,
			&i.FilePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
