// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: comments.sql

package store

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countCommentsByDocument = `-- name: CountCommentsByDocument :one
SELECT COUNT(*) FROM comments WHERE document_id = $1
`

func (q *Queries) CountCommentsByDocument(ctx context.Context, documentID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCommentsByDocument, documentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (document_id, author_id, content, heading_anchor, parent_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, document_id, author_id, content, heading_anchor, parent_id, created_at, updated_at
`

type CreateCommentParams struct {
	DocumentID    uuid.UUID      `json:"document_id"`
	AuthorID      uuid.UUID      `json:"author_id"`
	Content       string         `json:"content"`
	HeadingAnchor sql.NullString `json:"heading_anchor"`
	ParentID      uuid.NullUUID  `json:"parent_id"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment,
		arg.DocumentID,
		arg.AuthorID,
		arg.Content,
		arg.HeadingAnchor,
		arg.ParentID,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.AuthorID,
		&i.Content,
		&i.HeadingAnchor,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteComment, id)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, document_id, author_id, content, heading_anchor, parent_id, created_at, updated_at FROM comments WHERE id = $1
`

func (q *Queries) GetCommentByID(ctx context.Context, id uuid.UUID) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.AuthorID,
		&i.Content,
		&i.HeadingAnchor,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCommentReplies = `-- name: ListCommentReplies :many
SELECT id, document_id, author_id, content, heading_anchor, parent_id, created_at, updated_at FROM comments WHERE parent_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListCommentReplies(ctx context.Context, parentID uuid.NullUUID) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentReplies, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.AuthorID,
			&i.Content,
			&i.HeadingAnchor,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByAuthor = `-- name: ListCommentsByAuthor :many
SELECT id, document_id, author_id, content, heading_anchor, parent_id, created_at, updated_at FROM comments WHERE author_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListCommentsByAuthor(ctx context.Context, authorID uuid.UUID) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByAuthor, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.AuthorID,
			&i.Content,
			&i.HeadingAnchor,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByDocument = `-- name: ListCommentsByDocument :many
SELECT id, document_id, author_id, content, heading_anchor, parent_id, created_at, updated_at FROM comments
WHERE document_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListCommentsByDocument(ctx context.Context, documentID uuid.UUID) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.AuthorID,
			&i.Content,
			&i.HeadingAnchor,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByDocumentAndAnchor = `-- name: ListCommentsByDocumentAndAnchor :many
SELECT id, document_id, author_id, content, heading_anchor, parent_id, created_at, updated_at FROM comments
WHERE document_id = $1 AND heading_anchor = $2
ORDER BY created_at ASC
`

type ListCommentsByDocumentAndAnchorParams struct {
	DocumentID    uuid.UUID      `json:"document_id"`
	HeadingAnchor sql.NullString `json:"heading_anchor"`
}

func (q *Queries) ListCommentsByDocumentAndAnchor(ctx context.Context, arg ListCommentsByDocumentAndAnchorParams) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByDocumentAndAnchor, arg.DocumentID, arg.HeadingAnchor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.AuthorID,
			&i.Content,
			&i.HeadingAnchor,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentComments = `-- name: ListDocumentComments :many
SELECT id, document_id, author_id, content, heading_anchor, parent_id, created_at, updated_at FROM comments
WHERE document_id = $1 AND heading_anchor IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListDocumentComments(ctx context.Context, documentID uuid.UUID) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentComments, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.AuthorID,
			&i.Content,
			&i.HeadingAnchor,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments
SET content = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, document_id, author_id, content, heading_anchor, parent_id, created_at, updated_at
`

type UpdateCommentParams struct {
	ID      uuid.UUID `json:"id"`
	Content string    `json:"content"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, updateComment, arg.ID, arg.Content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.AuthorID,
		&i.Content,
		&i.HeadingAnchor,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
