// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: documents.sql

package store

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countAccessibleDocuments = `-- name: CountAccessibleDocuments :one
SELECT COUNT(DISTINCT d.id)
FROM documents d
LEFT JOIN document_permissions dp ON dp.document_id = d.id AND dp.user_id = $1
WHERE d.owner_id = $1 OR dp.user_id IS NOT NULL
`

func (q *Queries) CountAccessibleDocuments(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccessibleDocuments, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOwnedDocuments = `-- name: CountOwnedDocuments :one
SELECT COUNT(*) FROM documents WHERE owner_id = $1
`

func (q *Queries) CountOwnedDocuments(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOwnedDocuments, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (owner_id, parent_id, title, content, visibility, inherit_visibility, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, owner_id, title, content, is_public, sort_order, created_at, updated_at, parent_id, visibility, inherit_visibility
`

type CreateDocumentParams struct {
	OwnerID           uuid.UUID     `json:"owner_id"`
	ParentID          uuid.NullUUID `json:"parent_id"`
	Title             string        `json:"title"`
	Content           string        `json:"content"`
	Visibility        string        `json:"visibility"`
	InheritVisibility bool          `json:"inherit_visibility"`
	SortOrder         int32         `json:"sort_order"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.OwnerID,
		arg.ParentID,
		arg.Title,
		arg.Content,
		arg.Visibility,
		arg.InheritVisibility,
		arg.SortOrder,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Content,
		&i.IsPublic,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.Visibility,
		&i.InheritVisibility,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDocument, id)
	return err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, owner_id, title, content, is_public, sort_order, created_at, updated_at, parent_id, visibility, inherit_visibility FROM documents WHERE id = $1
`

func (q *Queries) GetDocumentByID(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Content,
		&i.IsPublic,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.Visibility,
		&i.InheritVisibility,
	)
	return i, err
}

const getDocumentPath = `-- name: GetDocumentPath :many
WITH RECURSIVE doc_path AS (
    SELECT d.id, d.parent_id, d.title, 1 as depth
    FROM documents d
    WHERE d.id = $1
    UNION ALL
    SELECT d.id, d.parent_id, d.title, dp.depth + 1
    FROM documents d
    JOIN doc_path dp ON d.id = dp.parent_id
)
SELECT id, parent_id, title, depth FROM doc_path ORDER BY depth
`

type GetDocumentPathRow struct {
	ID       uuid.UUID     `json:"id"`
	ParentID uuid.NullUUID `json:"parent_id"`
	Title    string        `json:"title"`
	Depth    int32         `json:"depth"`
}

func (q *Queries) GetDocumentPath(ctx context.Context, id uuid.UUID) ([]GetDocumentPathRow, error) {
	rows, err := q.db.QueryContext(ctx, getDocumentPath, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDocumentPathRow{}
	for rows.Next() {
		var i GetDocumentPathRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Title,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildDocuments = `-- name: ListChildDocuments :many
SELECT id, owner_id, title, content, is_public, sort_order, created_at, updated_at, parent_id, visibility, inherit_visibility FROM documents WHERE parent_id = $1 ORDER BY sort_order, updated_at DESC
`

func (q *Queries) ListChildDocuments(ctx context.Context, parentID uuid.NullUUID) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listChildDocuments, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Content,
			&i.IsPublic,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentID,
			&i.Visibility,
			&i.InheritVisibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByOwner = `-- name: ListDocumentsByOwner :many
SELECT id, owner_id, title, content, is_public, sort_order, created_at, updated_at, parent_id, visibility, inherit_visibility FROM documents WHERE owner_id = $1 ORDER BY sort_order, updated_at DESC
`

func (q *Queries) ListDocumentsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Content,
			&i.IsPublic,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentID,
			&i.Visibility,
			&i.InheritVisibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsWithPermission = `-- name: ListDocumentsWithPermission :many
SELECT DISTINCT d.id, d.owner_id, d.title, d.content, d.is_public, d.sort_order, d.created_at, d.updated_at, d.parent_id, d.visibility, d.inherit_visibility
FROM documents d
LEFT JOIN document_permissions dp ON dp.document_id = d.id AND dp.user_id = $1
WHERE d.owner_id = $1 OR dp.user_id IS NOT NULL
`

func (q *Queries) ListDocumentsWithPermission(ctx context.Context, userID uuid.UUID) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsWithPermission, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Content,
			&i.IsPublic,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentID,
			&i.Visibility,
			&i.InheritVisibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicDocuments = `-- name: ListPublicDocuments :many
SELECT id, owner_id, title, content, is_public, sort_order, created_at, updated_at, parent_id, visibility, inherit_visibility FROM documents WHERE visibility = 'public' ORDER BY updated_at DESC LIMIT 20
`

func (q *Queries) ListPublicDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listPublicDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Content,
			&i.IsPublic,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentID,
			&i.Visibility,
			&i.InheritVisibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootDocuments = `-- name: ListRootDocuments :many
SELECT id, owner_id, title, content, is_public, sort_order, created_at, updated_at, parent_id, visibility, inherit_visibility FROM documents WHERE parent_id IS NULL AND owner_id = $1 ORDER BY sort_order, updated_at DESC
`

func (q *Queries) ListRootDocuments(ctx context.Context, ownerID uuid.UUID) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listRootDocuments, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Content,
			&i.IsPublic,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentID,
			&i.Visibility,
			&i.InheritVisibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDocuments = `-- name: SearchDocuments :many
SELECT id, parent_id, title, content, owner_id, visibility, inherit_visibility, is_public, created_at, updated_at, sort_order
FROM documents
WHERE visibility = 'public'
  AND (title ILIKE '%' || $1 || '%' OR content ILIKE '%' || $1 || '%')
ORDER BY updated_at DESC
LIMIT 20
`

type SearchDocumentsRow struct {
	ID                uuid.UUID     `json:"id"`
	ParentID          uuid.NullUUID `json:"parent_id"`
	Title             string        `json:"title"`
	Content           string        `json:"content"`
	OwnerID           uuid.UUID     `json:"owner_id"`
	Visibility        string        `json:"visibility"`
	InheritVisibility bool          `json:"inherit_visibility"`
	IsPublic          bool          `json:"is_public"`
	CreatedAt         time.Time     `json:"created_at"`
	UpdatedAt         time.Time     `json:"updated_at"`
	SortOrder         int32         `json:"sort_order"`
}

func (q *Queries) SearchDocuments(ctx context.Context, dollar_1 sql.NullString) ([]SearchDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchDocuments, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchDocumentsRow{}
	for rows.Next() {
		var i SearchDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Title,
			&i.Content,
			&i.OwnerID,
			&i.Visibility,
			&i.InheritVisibility,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUserDocuments = `-- name: SearchUserDocuments :many
SELECT d.id, d.title, d.content, d.owner_id, d.visibility, d.is_public, d.created_at, d.updated_at, d.sort_order
FROM documents d
LEFT JOIN document_permissions dp ON dp.document_id = d.id AND dp.user_id = $1
WHERE (d.owner_id = $1 OR dp.user_id IS NOT NULL)
  AND (d.title ILIKE '%' || $2 || '%' OR d.content ILIKE '%' || $2 || '%')
ORDER BY d.updated_at DESC
LIMIT 20
`

type SearchUserDocumentsParams struct {
	UserID  uuid.UUID      `json:"user_id"`
	Column2 sql.NullString `json:"column_2"`
}

type SearchUserDocumentsRow struct {
	ID         uuid.UUID `json:"id"`
	Title      string    `json:"title"`
	Content    string    `json:"content"`
	OwnerID    uuid.UUID `json:"owner_id"`
	Visibility string    `json:"visibility"`
	IsPublic   bool      `json:"is_public"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
	SortOrder  int32     `json:"sort_order"`
}

func (q *Queries) SearchUserDocuments(ctx context.Context, arg SearchUserDocumentsParams) ([]SearchUserDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchUserDocuments, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUserDocumentsRow{}
	for rows.Next() {
		var i SearchUserDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.OwnerID,
			&i.Visibility,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentContent = `-- name: UpdateDocumentContent :one
UPDATE documents
SET content = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, title, content, is_public, sort_order, created_at, updated_at, parent_id, visibility, inherit_visibility
`

type UpdateDocumentContentParams struct {
	ID      uuid.UUID `json:"id"`
	Content string    `json:"content"`
}

func (q *Queries) UpdateDocumentContent(ctx context.Context, arg UpdateDocumentContentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, updateDocumentContent, arg.ID, arg.Content)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Content,
		&i.IsPublic,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.Visibility,
		&i.InheritVisibility,
	)
	return i, err
}

const updateDocumentParent = `-- name: UpdateDocumentParent :one
UPDATE documents
SET parent_id = $2, sort_order = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, title, content, is_public, sort_order, created_at, updated_at, parent_id, visibility, inherit_visibility
`

type UpdateDocumentParentParams struct {
	ID        uuid.UUID     `json:"id"`
	ParentID  uuid.NullUUID `json:"parent_id"`
	SortOrder int32         `json:"sort_order"`
}

func (q *Queries) UpdateDocumentParent(ctx context.Context, arg UpdateDocumentParentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, updateDocumentParent, arg.ID, arg.ParentID, arg.SortOrder)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Content,
		&i.IsPublic,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.Visibility,
		&i.InheritVisibility,
	)
	return i, err
}

const updateDocumentPublicStatus = `-- name: UpdateDocumentPublicStatus :one
UPDATE documents
SET is_public = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, title, content, is_public, sort_order, created_at, updated_at, parent_id, visibility, inherit_visibility
`

type UpdateDocumentPublicStatusParams struct {
	ID       uuid.UUID `json:"id"`
	IsPublic bool      `json:"is_public"`
}

func (q *Queries) UpdateDocumentPublicStatus(ctx context.Context, arg UpdateDocumentPublicStatusParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, updateDocumentPublicStatus, arg.ID, arg.IsPublic)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Content,
		&i.IsPublic,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.Visibility,
		&i.InheritVisibility,
	)
	return i, err
}

const updateDocumentSortOrder = `-- name: UpdateDocumentSortOrder :exec
UPDATE documents SET sort_order = $2, updated_at = NOW() WHERE id = $1
`

type UpdateDocumentSortOrderParams struct {
	ID        uuid.UUID `json:"id"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) UpdateDocumentSortOrder(ctx context.Context, arg UpdateDocumentSortOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateDocumentSortOrder, arg.ID, arg.SortOrder)
	return err
}

const updateDocumentTitle = `-- name: UpdateDocumentTitle :one
UPDATE documents
SET title = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, title, content, is_public, sort_order, created_at, updated_at, parent_id, visibility, inherit_visibility
`

type UpdateDocumentTitleParams struct {
	ID    uuid.UUID `json:"id"`
	Title string    `json:"title"`
}

func (q *Queries) UpdateDocumentTitle(ctx context.Context, arg UpdateDocumentTitleParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, updateDocumentTitle, arg.ID, arg.Title)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Content,
		&i.IsPublic,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.Visibility,
		&i.InheritVisibility,
	)
	return i, err
}

const updateDocumentVisibility = `-- name: UpdateDocumentVisibility :one
UPDATE documents
SET visibility = $2, inherit_visibility = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, title, content, is_public, sort_order, created_at, updated_at, parent_id, visibility, inherit_visibility
`

type UpdateDocumentVisibilityParams struct {
	ID                uuid.UUID `json:"id"`
	Visibility        string    `json:"visibility"`
	InheritVisibility bool      `json:"inherit_visibility"`
}

func (q *Queries) UpdateDocumentVisibility(ctx context.Context, arg UpdateDocumentVisibilityParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, updateDocumentVisibility, arg.ID, arg.Visibility, arg.InheritVisibility)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Content,
		&i.IsPublic,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.Visibility,
		&i.InheritVisibility,
	)
	return i, err
}
