// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: documents.sql

package store

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countAccessibleDocuments = `-- name: CountAccessibleDocuments :one
SELECT COUNT(DISTINCT d.id)
FROM documents d
LEFT JOIN workspace_members wm ON wm.workspace_id = d.workspace_id AND wm.user_id = $1
LEFT JOIN document_permissions dp ON dp.document_id = d.id AND dp.user_id = $1
WHERE wm.user_id IS NOT NULL OR dp.user_id IS NOT NULL
`

func (q *Queries) CountAccessibleDocuments(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccessibleDocuments, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOwnedDocuments = `-- name: CountOwnedDocuments :one
SELECT COUNT(*) FROM documents WHERE owner_id = $1
`

func (q *Queries) CountOwnedDocuments(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOwnedDocuments, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (owner_id, title, content, workspace_id)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, title, content, is_public, sort_order, created_at, updated_at, workspace_id
`

type CreateDocumentParams struct {
	OwnerID     uuid.UUID `json:"owner_id"`
	Title       string    `json:"title"`
	Content     string    `json:"content"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.OwnerID,
		arg.Title,
		arg.Content,
		arg.WorkspaceID,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Content,
		&i.IsPublic,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDocument, id)
	return err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, owner_id, title, content, is_public, sort_order, created_at, updated_at, workspace_id FROM documents WHERE id = $1
`

func (q *Queries) GetDocumentByID(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Content,
		&i.IsPublic,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const listDocumentsByOwner = `-- name: ListDocumentsByOwner :many
SELECT id, owner_id, title, content, is_public, sort_order, created_at, updated_at, workspace_id FROM documents WHERE owner_id = $1 ORDER BY updated_at DESC
`

func (q *Queries) ListDocumentsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Content,
			&i.IsPublic,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByWorkspace = `-- name: ListDocumentsByWorkspace :many
SELECT id, owner_id, title, content, is_public, sort_order, created_at, updated_at, workspace_id FROM documents WHERE workspace_id = $1 ORDER BY sort_order, updated_at DESC
`

func (q *Queries) ListDocumentsByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Content,
			&i.IsPublic,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicDocuments = `-- name: ListPublicDocuments :many
SELECT id, owner_id, title, content, is_public, sort_order, created_at, updated_at, workspace_id FROM documents WHERE is_public = true ORDER BY updated_at DESC LIMIT 20
`

func (q *Queries) ListPublicDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listPublicDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Content,
			&i.IsPublic,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDocuments = `-- name: SearchDocuments :many
SELECT d.id, d.title, d.content, d.workspace_id, d.owner_id, d.is_public, d.created_at, d.updated_at, d.sort_order,
       w.name as workspace_name
FROM documents d
LEFT JOIN workspaces w ON w.id = d.workspace_id
WHERE d.is_public = true
  AND (d.title ILIKE '%' || $1 || '%' OR d.content ILIKE '%' || $1 || '%')
ORDER BY d.updated_at DESC
LIMIT 20
`

type SearchDocumentsRow struct {
	ID            uuid.UUID      `json:"id"`
	Title         string         `json:"title"`
	Content       string         `json:"content"`
	WorkspaceID   uuid.UUID      `json:"workspace_id"`
	OwnerID       uuid.UUID      `json:"owner_id"`
	IsPublic      bool           `json:"is_public"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	SortOrder     int32          `json:"sort_order"`
	WorkspaceName sql.NullString `json:"workspace_name"`
}

func (q *Queries) SearchDocuments(ctx context.Context, dollar_1 sql.NullString) ([]SearchDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchDocuments, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchDocumentsRow{}
	for rows.Next() {
		var i SearchDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.WorkspaceID,
			&i.OwnerID,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SortOrder,
			&i.WorkspaceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUserDocuments = `-- name: SearchUserDocuments :many
SELECT d.id, d.title, d.content, d.workspace_id, d.owner_id, d.is_public, d.created_at, d.updated_at, d.sort_order,
       w.name as workspace_name
FROM documents d
LEFT JOIN workspaces w ON w.id = d.workspace_id
LEFT JOIN workspace_members wm ON wm.workspace_id = d.workspace_id
LEFT JOIN document_permissions dp ON dp.document_id = d.id AND dp.user_id = $1
WHERE (d.owner_id = $1 OR wm.user_id = $1 OR dp.user_id IS NOT NULL)
  AND (d.title ILIKE '%' || $2 || '%' OR d.content ILIKE '%' || $2 || '%')
ORDER BY d.updated_at DESC
LIMIT 20
`

type SearchUserDocumentsParams struct {
	UserID  uuid.UUID      `json:"user_id"`
	Column2 sql.NullString `json:"column_2"`
}

type SearchUserDocumentsRow struct {
	ID            uuid.UUID      `json:"id"`
	Title         string         `json:"title"`
	Content       string         `json:"content"`
	WorkspaceID   uuid.UUID      `json:"workspace_id"`
	OwnerID       uuid.UUID      `json:"owner_id"`
	IsPublic      bool           `json:"is_public"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	SortOrder     int32          `json:"sort_order"`
	WorkspaceName sql.NullString `json:"workspace_name"`
}

func (q *Queries) SearchUserDocuments(ctx context.Context, arg SearchUserDocumentsParams) ([]SearchUserDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchUserDocuments, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUserDocumentsRow{}
	for rows.Next() {
		var i SearchUserDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.WorkspaceID,
			&i.OwnerID,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SortOrder,
			&i.WorkspaceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentContent = `-- name: UpdateDocumentContent :one
UPDATE documents
SET content = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, title, content, is_public, sort_order, created_at, updated_at, workspace_id
`

type UpdateDocumentContentParams struct {
	ID      uuid.UUID `json:"id"`
	Content string    `json:"content"`
}

func (q *Queries) UpdateDocumentContent(ctx context.Context, arg UpdateDocumentContentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, updateDocumentContent, arg.ID, arg.Content)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Content,
		&i.IsPublic,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const updateDocumentPublicStatus = `-- name: UpdateDocumentPublicStatus :one
UPDATE documents
SET is_public = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, title, content, is_public, sort_order, created_at, updated_at, workspace_id
`

type UpdateDocumentPublicStatusParams struct {
	ID       uuid.UUID `json:"id"`
	IsPublic bool      `json:"is_public"`
}

func (q *Queries) UpdateDocumentPublicStatus(ctx context.Context, arg UpdateDocumentPublicStatusParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, updateDocumentPublicStatus, arg.ID, arg.IsPublic)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Content,
		&i.IsPublic,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const updateDocumentSortOrder = `-- name: UpdateDocumentSortOrder :exec
UPDATE documents SET sort_order = $2, updated_at = NOW() WHERE id = $1
`

type UpdateDocumentSortOrderParams struct {
	ID        uuid.UUID `json:"id"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) UpdateDocumentSortOrder(ctx context.Context, arg UpdateDocumentSortOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateDocumentSortOrder, arg.ID, arg.SortOrder)
	return err
}

const updateDocumentTitle = `-- name: UpdateDocumentTitle :one
UPDATE documents
SET title = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, title, content, is_public, sort_order, created_at, updated_at, workspace_id
`

type UpdateDocumentTitleParams struct {
	ID    uuid.UUID `json:"id"`
	Title string    `json:"title"`
}

func (q *Queries) UpdateDocumentTitle(ctx context.Context, arg UpdateDocumentTitleParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, updateDocumentTitle, arg.ID, arg.Title)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Content,
		&i.IsPublic,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}
