// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type PermissionLevel string

const (
	PermissionLevelRead   PermissionLevel = "read"
	PermissionLevelEdit   PermissionLevel = "edit"
	PermissionLevelManage PermissionLevel = "manage"
)

func (e *PermissionLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PermissionLevel(s)
	case string:
		*e = PermissionLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for PermissionLevel: %T", src)
	}
	return nil
}

type NullPermissionLevel struct {
	PermissionLevel PermissionLevel `json:"permission_level"`
	Valid           bool            `json:"valid"` // Valid is true if PermissionLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPermissionLevel) Scan(value interface{}) error {
	if value == nil {
		ns.PermissionLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PermissionLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPermissionLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PermissionLevel), nil
}

type AdminLog struct {
	ID             uuid.UUID             `json:"id"`
	AdminID        uuid.UUID             `json:"admin_id"`
	Action         string                `json:"action"`
	TargetType     string                `json:"target_type"`
	TargetID       uuid.NullUUID         `json:"target_id"`
	TargetUsername sql.NullString        `json:"target_username"`
	Details        pqtype.NullRawMessage `json:"details"`
	IpAddress      sql.NullString        `json:"ip_address"`
	UserAgent      sql.NullString        `json:"user_agent"`
	CreatedAt      time.Time             `json:"created_at"`
}

type Attachment struct {
	ID          uuid.UUID     `json:"id"`
	DocumentID  uuid.NullUUID `json:"document_id"`
	UploadBy    uuid.UUID     `json:"upload_by"`
	Filename    string        `json:"filename"`
	FileType    string        `json:"file_type"`
	FileSize    int64         `json:"file_size"`
	FilePath    string        `json:"file_path"`
	CreatedAt   time.Time     `json:"created_at"`
	WorkspaceID uuid.UUID     `json:"workspace_id"`
}

type AttachmentReference struct {
	ID           uuid.UUID `json:"id"`
	AttachmentID uuid.UUID `json:"attachment_id"`
	DocumentID   uuid.UUID `json:"document_id"`
	ReferencedAt int32     `json:"referenced_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type Document struct {
	ID          uuid.UUID `json:"id"`
	OwnerID     uuid.UUID `json:"owner_id"`
	Title       string    `json:"title"`
	Content     string    `json:"content"`
	IsPublic    bool      `json:"is_public"`
	SortOrder   int32     `json:"sort_order"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

type DocumentPermission struct {
	ID         uuid.UUID       `json:"id"`
	DocumentID uuid.UUID       `json:"document_id"`
	UserID     uuid.UUID       `json:"user_id"`
	Level      PermissionLevel `json:"level"`
	CreatedAt  time.Time       `json:"created_at"`
}

type HeadingPermission struct {
	ID            uuid.UUID       `json:"id"`
	DocumentID    uuid.UUID       `json:"document_id"`
	UserID        uuid.UUID       `json:"user_id"`
	HeadingAnchor string          `json:"heading_anchor"`
	Level         PermissionLevel `json:"level"`
	CreatedAt     time.Time       `json:"created_at"`
}

type Snapshot struct {
	ID         uuid.UUID     `json:"id"`
	DocumentID uuid.UUID     `json:"document_id"`
	AuthorID   uuid.NullUUID `json:"author_id"`
	Content    string        `json:"content"`
	Message    string        `json:"message"`
	CreatedAt  time.Time     `json:"created_at"`
}

type User struct {
	ID                uuid.UUID      `json:"id"`
	Username          string         `json:"username"`
	Email             sql.NullString `json:"email"`
	PasswordHash      string         `json:"password_hash"`
	PreferredLanguage string         `json:"preferred_language"`
	IsAdmin           bool           `json:"is_admin"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	IsActive          bool           `json:"is_active"`
}

type Workspace struct {
	ID        uuid.UUID `json:"id"`
	OwnerID   uuid.UUID `json:"owner_id"`
	Name      string    `json:"name"`
	IsPublic  bool      `json:"is_public"`
	SortOrder int32     `json:"sort_order"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type WorkspaceMember struct {
	ID          uuid.UUID       `json:"id"`
	WorkspaceID uuid.UUID       `json:"workspace_id"`
	UserID      uuid.UUID       `json:"user_id"`
	Level       PermissionLevel `json:"level"`
	CreatedAt   time.Time       `json:"created_at"`
}
