// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type PermissionLevel string

const (
	PermissionLevelRead   PermissionLevel = "read"
	PermissionLevelEdit   PermissionLevel = "edit"
	PermissionLevelManage PermissionLevel = "manage"
)

func (e *PermissionLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PermissionLevel(s)
	case string:
		*e = PermissionLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for PermissionLevel: %T", src)
	}
	return nil
}

type NullPermissionLevel struct {
	PermissionLevel PermissionLevel `json:"permission_level"`
	Valid           bool            `json:"valid"` // Valid is true if PermissionLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPermissionLevel) Scan(value interface{}) error {
	if value == nil {
		ns.PermissionLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PermissionLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPermissionLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PermissionLevel), nil
}

type AdminLog struct {
	ID             uuid.UUID             `json:"id"`
	AdminID        uuid.UUID             `json:"admin_id"`
	Action         string                `json:"action"`
	TargetType     string                `json:"target_type"`
	TargetID       uuid.NullUUID         `json:"target_id"`
	TargetUsername sql.NullString        `json:"target_username"`
	Details        pqtype.NullRawMessage `json:"details"`
	IpAddress      sql.NullString        `json:"ip_address"`
	UserAgent      sql.NullString        `json:"user_agent"`
	CreatedAt      time.Time             `json:"created_at"`
}

type AiConversation struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	DocumentID uuid.UUID `json:"document_id"`
	Title      string    `json:"title"`
	CreatedAt  time.Time `json:"created_at"`
}

type AiMessage struct {
	ID             uuid.UUID `json:"id"`
	ConversationID uuid.UUID `json:"conversation_id"`
	Role           string    `json:"role"`
	Content        string    `json:"content"`
	CreatedAt      time.Time `json:"created_at"`
}

type Attachment struct {
	ID         uuid.UUID     `json:"id"`
	DocumentID uuid.NullUUID `json:"document_id"`
	UploadBy   uuid.UUID     `json:"upload_by"`
	Filename   string        `json:"filename"`
	FileType   string        `json:"file_type"`
	FileSize   int64         `json:"file_size"`
	FilePath   string        `json:"file_path"`
	CreatedAt  time.Time     `json:"created_at"`
}

type AttachmentReference struct {
	ID           uuid.UUID `json:"id"`
	AttachmentID uuid.UUID `json:"attachment_id"`
	DocumentID   uuid.UUID `json:"document_id"`
	ReferencedAt int32     `json:"referenced_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type Comment struct {
	ID            uuid.UUID      `json:"id"`
	DocumentID    uuid.UUID      `json:"document_id"`
	AuthorID      uuid.UUID      `json:"author_id"`
	Content       string         `json:"content"`
	HeadingAnchor sql.NullString `json:"heading_anchor"`
	ParentID      uuid.NullUUID  `json:"parent_id"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type Document struct {
	ID                uuid.UUID     `json:"id"`
	OwnerID           uuid.UUID     `json:"owner_id"`
	Title             string        `json:"title"`
	Content           string        `json:"content"`
	IsPublic          bool          `json:"is_public"`
	SortOrder         int32         `json:"sort_order"`
	CreatedAt         time.Time     `json:"created_at"`
	UpdatedAt         time.Time     `json:"updated_at"`
	ParentID          uuid.NullUUID `json:"parent_id"`
	Visibility        string        `json:"visibility"`
	InheritVisibility bool          `json:"inherit_visibility"`
}

type DocumentPermission struct {
	ID         uuid.UUID       `json:"id"`
	DocumentID uuid.UUID       `json:"document_id"`
	UserID     uuid.UUID       `json:"user_id"`
	Level      PermissionLevel `json:"level"`
	CreatedAt  time.Time       `json:"created_at"`
}

type HeadingPermission struct {
	ID            uuid.UUID       `json:"id"`
	DocumentID    uuid.UUID       `json:"document_id"`
	UserID        uuid.UUID       `json:"user_id"`
	HeadingAnchor string          `json:"heading_anchor"`
	Level         PermissionLevel `json:"level"`
	CreatedAt     time.Time       `json:"created_at"`
}

type Setting struct {
	Key         string         `json:"key"`
	Value       string         `json:"value"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Snapshot struct {
	ID         uuid.UUID     `json:"id"`
	DocumentID uuid.UUID     `json:"document_id"`
	AuthorID   uuid.NullUUID `json:"author_id"`
	Content    string        `json:"content"`
	Message    string        `json:"message"`
	CreatedAt  time.Time     `json:"created_at"`
}

type SocialAccount struct {
	ID               uuid.UUID      `json:"id"`
	UserID           uuid.UUID      `json:"user_id"`
	Provider         string         `json:"provider"`
	ExternalUserID   string         `json:"external_user_id"`
	ExternalNickname sql.NullString `json:"external_nickname"`
	AccessToken      sql.NullString `json:"access_token"`
	RefreshToken     sql.NullString `json:"refresh_token"`
	TokenExpiresAt   sql.NullTime   `json:"token_expires_at"`
	BoundAt          time.Time      `json:"bound_at"`
}

type User struct {
	ID                uuid.UUID      `json:"id"`
	Username          string         `json:"username"`
	Email             sql.NullString `json:"email"`
	PasswordHash      string         `json:"password_hash"`
	PreferredLanguage string         `json:"preferred_language"`
	IsAdmin           bool           `json:"is_admin"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	IsActive          bool           `json:"is_active"`
}
