// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: permissions.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteDocumentPermission = `-- name: DeleteDocumentPermission :exec
DELETE FROM document_permissions WHERE document_id = $1 AND user_id = $2
`

type DeleteDocumentPermissionParams struct {
	DocumentID uuid.UUID `json:"document_id"`
	UserID     uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteDocumentPermission(ctx context.Context, arg DeleteDocumentPermissionParams) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentPermission, arg.DocumentID, arg.UserID)
	return err
}

const deleteHeadingPermission = `-- name: DeleteHeadingPermission :exec
DELETE FROM heading_permissions
WHERE document_id = $1 AND user_id = $2 AND heading_anchor = $3
`

type DeleteHeadingPermissionParams struct {
	DocumentID    uuid.UUID `json:"document_id"`
	UserID        uuid.UUID `json:"user_id"`
	HeadingAnchor string    `json:"heading_anchor"`
}

func (q *Queries) DeleteHeadingPermission(ctx context.Context, arg DeleteHeadingPermissionParams) error {
	_, err := q.db.ExecContext(ctx, deleteHeadingPermission, arg.DocumentID, arg.UserID, arg.HeadingAnchor)
	return err
}

const getDocumentPermission = `-- name: GetDocumentPermission :one
SELECT id, document_id, user_id, level, created_at FROM document_permissions
WHERE document_id = $1 AND user_id = $2
`

type GetDocumentPermissionParams struct {
	DocumentID uuid.UUID `json:"document_id"`
	UserID     uuid.UUID `json:"user_id"`
}

func (q *Queries) GetDocumentPermission(ctx context.Context, arg GetDocumentPermissionParams) (DocumentPermission, error) {
	row := q.db.QueryRowContext(ctx, getDocumentPermission, arg.DocumentID, arg.UserID)
	var i DocumentPermission
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.UserID,
		&i.Level,
		&i.CreatedAt,
	)
	return i, err
}

const getDocumentPermissionByUsername = `-- name: GetDocumentPermissionByUsername :one
SELECT dp.id, dp.document_id, dp.user_id, dp.level, dp.created_at FROM document_permissions dp
JOIN users u ON dp.user_id = u.id
WHERE dp.document_id = $1 AND u.username = $2
`

type GetDocumentPermissionByUsernameParams struct {
	DocumentID uuid.UUID `json:"document_id"`
	Username   string    `json:"username"`
}

func (q *Queries) GetDocumentPermissionByUsername(ctx context.Context, arg GetDocumentPermissionByUsernameParams) (DocumentPermission, error) {
	row := q.db.QueryRowContext(ctx, getDocumentPermissionByUsername, arg.DocumentID, arg.Username)
	var i DocumentPermission
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.UserID,
		&i.Level,
		&i.CreatedAt,
	)
	return i, err
}

const getHeadingPermission = `-- name: GetHeadingPermission :one
SELECT id, document_id, user_id, heading_anchor, level, created_at FROM heading_permissions
WHERE document_id = $1 AND user_id = $2 AND heading_anchor = $3
`

type GetHeadingPermissionParams struct {
	DocumentID    uuid.UUID `json:"document_id"`
	UserID        uuid.UUID `json:"user_id"`
	HeadingAnchor string    `json:"heading_anchor"`
}

func (q *Queries) GetHeadingPermission(ctx context.Context, arg GetHeadingPermissionParams) (HeadingPermission, error) {
	row := q.db.QueryRowContext(ctx, getHeadingPermission, arg.DocumentID, arg.UserID, arg.HeadingAnchor)
	var i HeadingPermission
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.UserID,
		&i.HeadingAnchor,
		&i.Level,
		&i.CreatedAt,
	)
	return i, err
}

const listDocumentPermissions = `-- name: ListDocumentPermissions :many
SELECT id, document_id, user_id, level, created_at FROM document_permissions WHERE document_id = $1
`

func (q *Queries) ListDocumentPermissions(ctx context.Context, documentID uuid.UUID) ([]DocumentPermission, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentPermissions, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentPermission{}
	for rows.Next() {
		var i DocumentPermission
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.UserID,
			&i.Level,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeadingPermissions = `-- name: ListHeadingPermissions :many
SELECT id, document_id, user_id, heading_anchor, level, created_at FROM heading_permissions
WHERE document_id = $1 AND user_id = $2
`

type ListHeadingPermissionsParams struct {
	DocumentID uuid.UUID `json:"document_id"`
	UserID     uuid.UUID `json:"user_id"`
}

func (q *Queries) ListHeadingPermissions(ctx context.Context, arg ListHeadingPermissionsParams) ([]HeadingPermission, error) {
	rows, err := q.db.QueryContext(ctx, listHeadingPermissions, arg.DocumentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HeadingPermission{}
	for rows.Next() {
		var i HeadingPermission
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.UserID,
			&i.HeadingAnchor,
			&i.Level,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsWithUsername = `-- name: ListPermissionsWithUsername :many
SELECT 
    dp.id, 
    dp.document_id, 
    dp.user_id, 
    dp.level, 
    dp.created_at,
    u.username
FROM document_permissions dp
JOIN users u ON dp.user_id = u.id
WHERE dp.document_id = $1
`

type ListPermissionsWithUsernameRow struct {
	ID         uuid.UUID       `json:"id"`
	DocumentID uuid.UUID       `json:"document_id"`
	UserID     uuid.UUID       `json:"user_id"`
	Level      PermissionLevel `json:"level"`
	CreatedAt  time.Time       `json:"created_at"`
	Username   string          `json:"username"`
}

func (q *Queries) ListPermissionsWithUsername(ctx context.Context, documentID uuid.UUID) ([]ListPermissionsWithUsernameRow, error) {
	rows, err := q.db.QueryContext(ctx, listPermissionsWithUsername, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPermissionsWithUsernameRow{}
	for rows.Next() {
		var i ListPermissionsWithUsernameRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.UserID,
			&i.Level,
			&i.CreatedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDocumentPermission = `-- name: UpsertDocumentPermission :one
INSERT INTO document_permissions (document_id, user_id, level)
VALUES ($1, $2, $3)
ON CONFLICT (document_id, user_id)
DO UPDATE SET level = EXCLUDED.level
RETURNING id, document_id, user_id, level, created_at
`

type UpsertDocumentPermissionParams struct {
	DocumentID uuid.UUID       `json:"document_id"`
	UserID     uuid.UUID       `json:"user_id"`
	Level      PermissionLevel `json:"level"`
}

func (q *Queries) UpsertDocumentPermission(ctx context.Context, arg UpsertDocumentPermissionParams) (DocumentPermission, error) {
	row := q.db.QueryRowContext(ctx, upsertDocumentPermission, arg.DocumentID, arg.UserID, arg.Level)
	var i DocumentPermission
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.UserID,
		&i.Level,
		&i.CreatedAt,
	)
	return i, err
}

const upsertHeadingPermission = `-- name: UpsertHeadingPermission :one
INSERT INTO heading_permissions (document_id, user_id, heading_anchor, level)
VALUES ($1, $2, $3, $4)
ON CONFLICT (document_id, user_id, heading_anchor)
DO UPDATE SET level = EXCLUDED.level
RETURNING id, document_id, user_id, heading_anchor, level, created_at
`

type UpsertHeadingPermissionParams struct {
	DocumentID    uuid.UUID       `json:"document_id"`
	UserID        uuid.UUID       `json:"user_id"`
	HeadingAnchor string          `json:"heading_anchor"`
	Level         PermissionLevel `json:"level"`
}

func (q *Queries) UpsertHeadingPermission(ctx context.Context, arg UpsertHeadingPermissionParams) (HeadingPermission, error) {
	row := q.db.QueryRowContext(ctx, upsertHeadingPermission,
		arg.DocumentID,
		arg.UserID,
		arg.HeadingAnchor,
		arg.Level,
	)
	var i HeadingPermission
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.UserID,
		&i.HeadingAnchor,
		&i.Level,
		&i.CreatedAt,
	)
	return i, err
}
