// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CountAccessibleDocuments(ctx context.Context, userID uuid.UUID) (int64, error)
	CountAdminLogs(ctx context.Context) (int64, error)
	CountAttachmentsUploaded(ctx context.Context, uploadBy uuid.UUID) (int64, error)
	CountOwnedDocuments(ctx context.Context, ownerID uuid.UUID) (int64, error)
	CountSnapshotsAuthored(ctx context.Context, authorID uuid.NullUUID) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountWorkspacesByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateAdminLog(ctx context.Context, arg CreateAdminLogParams) (AdminLog, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error)
	CreateAttachmentReference(ctx context.Context, arg CreateAttachmentReferenceParams) (AttachmentReference, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (Snapshot, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateUserWithAdmin(ctx context.Context, arg CreateUserWithAdminParams) (CreateUserWithAdminRow, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	DeleteAllWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) error
	DeleteAttachment(ctx context.Context, id uuid.UUID) error
	DeleteAttachmentReference(ctx context.Context, arg DeleteAttachmentReferenceParams) error
	DeleteDocument(ctx context.Context, id uuid.UUID) error
	DeleteDocumentPermission(ctx context.Context, arg DeleteDocumentPermissionParams) error
	DeleteHeadingPermission(ctx context.Context, arg DeleteHeadingPermissionParams) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteWorkspace(ctx context.Context, id uuid.UUID) error
	DeleteWorkspaceMember(ctx context.Context, arg DeleteWorkspaceMemberParams) error
	GetAllSettings(ctx context.Context) ([]Setting, error)
	GetAttachmentByID(ctx context.Context, id uuid.UUID) (Attachment, error)
	GetDocumentByID(ctx context.Context, id uuid.UUID) (Document, error)
	GetDocumentPermission(ctx context.Context, arg GetDocumentPermissionParams) (DocumentPermission, error)
	GetDocumentPermissionByUsername(ctx context.Context, arg GetDocumentPermissionByUsernameParams) (DocumentPermission, error)
	GetHeadingPermission(ctx context.Context, arg GetHeadingPermissionParams) (HeadingPermission, error)
	GetLatestSnapshot(ctx context.Context, documentID uuid.UUID) (Snapshot, error)
	GetSettingByKey(ctx context.Context, key string) (Setting, error)
	GetSnapshotByID(ctx context.Context, id uuid.UUID) (Snapshot, error)
	GetUnreferencedAttachments(ctx context.Context, documentID uuid.NullUUID) ([]Attachment, error)
	GetUserByEmail(ctx context.Context, email sql.NullString) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	GetWorkspaceByID(ctx context.Context, id uuid.UUID) (Workspace, error)
	GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (WorkspaceMember, error)
	ListAdminLogs(ctx context.Context, arg ListAdminLogsParams) ([]ListAdminLogsRow, error)
	ListAdminLogsByAdmin(ctx context.Context, arg ListAdminLogsByAdminParams) ([]ListAdminLogsByAdminRow, error)
	ListAttachmentReferences(ctx context.Context, attachmentID uuid.UUID) ([]AttachmentReference, error)
	ListDocumentAttachmentReferences(ctx context.Context, documentID uuid.NullUUID) ([]AttachmentReference, error)
	ListDocumentAttachments(ctx context.Context, documentID uuid.NullUUID) ([]Attachment, error)
	ListDocumentPermissions(ctx context.Context, documentID uuid.UUID) ([]DocumentPermission, error)
	ListDocumentsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Document, error)
	ListDocumentsByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Document, error)
	ListDocumentsWithPermission(ctx context.Context, userID uuid.UUID) ([]Document, error)
	ListHeadingPermissions(ctx context.Context, arg ListHeadingPermissionsParams) ([]HeadingPermission, error)
	ListPermissionsWithUsername(ctx context.Context, documentID uuid.UUID) ([]ListPermissionsWithUsernameRow, error)
	ListPublicDocuments(ctx context.Context) ([]Document, error)
	ListPublicWorkspaces(ctx context.Context) ([]Workspace, error)
	ListSnapshotsByDocument(ctx context.Context, arg ListSnapshotsByDocumentParams) ([]Snapshot, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	ListWorkspaceAttachments(ctx context.Context, workspaceID uuid.UUID) ([]Attachment, error)
	ListWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) ([]ListWorkspaceMembersRow, error)
	ListWorkspacesByMember(ctx context.Context, userID uuid.UUID) ([]Workspace, error)
	ListWorkspacesByOwner(ctx context.Context, ownerID uuid.UUID) ([]Workspace, error)
	UpdateDocumentContent(ctx context.Context, arg UpdateDocumentContentParams) (Document, error)
	UpdateDocumentPublicStatus(ctx context.Context, arg UpdateDocumentPublicStatusParams) (Document, error)
	UpdateDocumentSortOrder(ctx context.Context, arg UpdateDocumentSortOrderParams) error
	UpdateDocumentTitle(ctx context.Context, arg UpdateDocumentTitleParams) (Document, error)
	UpdateUserActive(ctx context.Context, arg UpdateUserActiveParams) (UpdateUserActiveRow, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (UpdateUserEmailRow, error)
	UpdateUserIsAdmin(ctx context.Context, arg UpdateUserIsAdminParams) (UpdateUserIsAdminRow, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserPreferredLanguage(ctx context.Context, arg UpdateUserPreferredLanguageParams) (UpdateUserPreferredLanguageRow, error)
	UpdateWorkspaceName(ctx context.Context, arg UpdateWorkspaceNameParams) (Workspace, error)
	UpdateWorkspacePublicStatus(ctx context.Context, arg UpdateWorkspacePublicStatusParams) (Workspace, error)
	UpdateWorkspaceSortOrder(ctx context.Context, arg UpdateWorkspaceSortOrderParams) error
	UpsertDocumentPermission(ctx context.Context, arg UpsertDocumentPermissionParams) (DocumentPermission, error)
	UpsertHeadingPermission(ctx context.Context, arg UpsertHeadingPermissionParams) (HeadingPermission, error)
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
	UpsertWorkspaceMember(ctx context.Context, arg UpsertWorkspaceMemberParams) (WorkspaceMember, error)
}

var _ Querier = (*Queries)(nil)
