// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: snapshots.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countSnapshotsAuthored = `-- name: CountSnapshotsAuthored :one
SELECT COUNT(*) FROM snapshots WHERE author_id = $1
`

func (q *Queries) CountSnapshotsAuthored(ctx context.Context, authorID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSnapshotsAuthored, authorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSnapshot = `-- name: CreateSnapshot :one
INSERT INTO snapshots (document_id, author_id, content, message)
VALUES ($1, $2, $3, $4)
RETURNING id, document_id, author_id, content, message, created_at
`

type CreateSnapshotParams struct {
	DocumentID uuid.UUID     `json:"document_id"`
	AuthorID   uuid.NullUUID `json:"author_id"`
	Content    string        `json:"content"`
	Message    string        `json:"message"`
}

func (q *Queries) CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, createSnapshot,
		arg.DocumentID,
		arg.AuthorID,
		arg.Content,
		arg.Message,
	)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.AuthorID,
		&i.Content,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestSnapshot = `-- name: GetLatestSnapshot :one
SELECT id, document_id, author_id, content, message, created_at FROM snapshots
WHERE document_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestSnapshot(ctx context.Context, documentID uuid.UUID) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, getLatestSnapshot, documentID)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.AuthorID,
		&i.Content,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const getSnapshotByID = `-- name: GetSnapshotByID :one
SELECT id, document_id, author_id, content, message, created_at FROM snapshots WHERE id = $1
`

func (q *Queries) GetSnapshotByID(ctx context.Context, id uuid.UUID) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, getSnapshotByID, id)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.AuthorID,
		&i.Content,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const listSnapshotsByDocument = `-- name: ListSnapshotsByDocument :many
SELECT id, document_id, author_id, content, message, created_at FROM snapshots
WHERE document_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSnapshotsByDocumentParams struct {
	DocumentID uuid.UUID `json:"document_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListSnapshotsByDocument(ctx context.Context, arg ListSnapshotsByDocumentParams) ([]Snapshot, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotsByDocument, arg.DocumentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Snapshot{}
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.AuthorID,
			&i.Content,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
