// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: social_accounts.sql

package store

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createSocialAccount = `-- name: CreateSocialAccount :one
INSERT INTO social_accounts (user_id, provider, external_user_id, external_nickname, access_token, refresh_token, token_expires_at, bound_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
RETURNING id, user_id, provider, external_user_id, external_nickname, access_token, refresh_token, token_expires_at, bound_at
`

type CreateSocialAccountParams struct {
	UserID           uuid.UUID      `json:"user_id"`
	Provider         string         `json:"provider"`
	ExternalUserID   string         `json:"external_user_id"`
	ExternalNickname sql.NullString `json:"external_nickname"`
	AccessToken      sql.NullString `json:"access_token"`
	RefreshToken     sql.NullString `json:"refresh_token"`
	TokenExpiresAt   sql.NullTime   `json:"token_expires_at"`
}

func (q *Queries) CreateSocialAccount(ctx context.Context, arg CreateSocialAccountParams) (SocialAccount, error) {
	row := q.db.QueryRowContext(ctx, createSocialAccount,
		arg.UserID,
		arg.Provider,
		arg.ExternalUserID,
		arg.ExternalNickname,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
	)
	var i SocialAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ExternalUserID,
		&i.ExternalNickname,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.BoundAt,
	)
	return i, err
}

const deleteSocialAccount = `-- name: DeleteSocialAccount :exec
DELETE FROM social_accounts WHERE user_id = $1 AND provider = $2
`

type DeleteSocialAccountParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Provider string    `json:"provider"`
}

func (q *Queries) DeleteSocialAccount(ctx context.Context, arg DeleteSocialAccountParams) error {
	_, err := q.db.ExecContext(ctx, deleteSocialAccount, arg.UserID, arg.Provider)
	return err
}

const deleteSocialAccountByID = `-- name: DeleteSocialAccountByID :exec
DELETE FROM social_accounts WHERE id = $1
`

func (q *Queries) DeleteSocialAccountByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSocialAccountByID, id)
	return err
}

const getSocialAccountByProviderAndExternalID = `-- name: GetSocialAccountByProviderAndExternalID :one
SELECT id, user_id, provider, external_user_id, external_nickname, access_token, refresh_token, token_expires_at, bound_at
FROM social_accounts
WHERE provider = $1 AND external_user_id = $2
`

type GetSocialAccountByProviderAndExternalIDParams struct {
	Provider       string `json:"provider"`
	ExternalUserID string `json:"external_user_id"`
}

func (q *Queries) GetSocialAccountByProviderAndExternalID(ctx context.Context, arg GetSocialAccountByProviderAndExternalIDParams) (SocialAccount, error) {
	row := q.db.QueryRowContext(ctx, getSocialAccountByProviderAndExternalID, arg.Provider, arg.ExternalUserID)
	var i SocialAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ExternalUserID,
		&i.ExternalNickname,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.BoundAt,
	)
	return i, err
}

const getSocialAccountByUserAndProvider = `-- name: GetSocialAccountByUserAndProvider :one
SELECT id, user_id, provider, external_user_id, external_nickname, access_token, refresh_token, token_expires_at, bound_at
FROM social_accounts
WHERE user_id = $1 AND provider = $2
`

type GetSocialAccountByUserAndProviderParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Provider string    `json:"provider"`
}

func (q *Queries) GetSocialAccountByUserAndProvider(ctx context.Context, arg GetSocialAccountByUserAndProviderParams) (SocialAccount, error) {
	row := q.db.QueryRowContext(ctx, getSocialAccountByUserAndProvider, arg.UserID, arg.Provider)
	var i SocialAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ExternalUserID,
		&i.ExternalNickname,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.BoundAt,
	)
	return i, err
}

const listSocialAccountsByUser = `-- name: ListSocialAccountsByUser :many
SELECT id, user_id, provider, external_user_id, external_nickname, access_token, refresh_token, token_expires_at, bound_at
FROM social_accounts
WHERE user_id = $1
`

func (q *Queries) ListSocialAccountsByUser(ctx context.Context, userID uuid.UUID) ([]SocialAccount, error) {
	rows, err := q.db.QueryContext(ctx, listSocialAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SocialAccount{}
	for rows.Next() {
		var i SocialAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ExternalUserID,
			&i.ExternalNickname,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiresAt,
			&i.BoundAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
