// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package store

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash)
VALUES ($1, $3, $2)
RETURNING id, username, email, password_hash, preferred_language, is_admin, created_at, updated_at
`

type CreateUserParams struct {
	Username     string         `json:"username"`
	PasswordHash string         `json:"password_hash"`
	Email        sql.NullString `json:"email"`
}

type CreateUserRow struct {
	ID                uuid.UUID      `json:"id"`
	Username          string         `json:"username"`
	Email             sql.NullString `json:"email"`
	PasswordHash      string         `json:"password_hash"`
	PreferredLanguage string         `json:"preferred_language"`
	IsAdmin           bool           `json:"is_admin"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.PasswordHash, arg.Email)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.PreferredLanguage,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserWithAdmin = `-- name: CreateUserWithAdmin :one
INSERT INTO users (username, email, password_hash, is_admin)
VALUES ($1, $4, $2, $3)
RETURNING id, username, email, password_hash, preferred_language, is_admin, created_at, updated_at
`

type CreateUserWithAdminParams struct {
	Username     string         `json:"username"`
	PasswordHash string         `json:"password_hash"`
	IsAdmin      bool           `json:"is_admin"`
	Email        sql.NullString `json:"email"`
}

type CreateUserWithAdminRow struct {
	ID                uuid.UUID      `json:"id"`
	Username          string         `json:"username"`
	Email             sql.NullString `json:"email"`
	PasswordHash      string         `json:"password_hash"`
	PreferredLanguage string         `json:"preferred_language"`
	IsAdmin           bool           `json:"is_admin"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

func (q *Queries) CreateUserWithAdmin(ctx context.Context, arg CreateUserWithAdminParams) (CreateUserWithAdminRow, error) {
	row := q.db.QueryRowContext(ctx, createUserWithAdmin,
		arg.Username,
		arg.PasswordHash,
		arg.IsAdmin,
		arg.Email,
	)
	var i CreateUserWithAdminRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.PreferredLanguage,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, preferred_language, is_admin, created_at, updated_at FROM users WHERE email = $1
`

type GetUserByEmailRow struct {
	ID                uuid.UUID      `json:"id"`
	Username          string         `json:"username"`
	Email             sql.NullString `json:"email"`
	PasswordHash      string         `json:"password_hash"`
	PreferredLanguage string         `json:"preferred_language"`
	IsAdmin           bool           `json:"is_admin"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email sql.NullString) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.PreferredLanguage,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, preferred_language, is_admin, created_at, updated_at FROM users WHERE id = $1
`

type GetUserByIDRow struct {
	ID                uuid.UUID      `json:"id"`
	Username          string         `json:"username"`
	Email             sql.NullString `json:"email"`
	PasswordHash      string         `json:"password_hash"`
	PreferredLanguage string         `json:"preferred_language"`
	IsAdmin           bool           `json:"is_admin"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.PreferredLanguage,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, preferred_language, is_admin, created_at, updated_at FROM users WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID                uuid.UUID      `json:"id"`
	Username          string         `json:"username"`
	Email             sql.NullString `json:"email"`
	PasswordHash      string         `json:"password_hash"`
	PreferredLanguage string         `json:"preferred_language"`
	IsAdmin           bool           `json:"is_admin"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.PreferredLanguage,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, password_hash, preferred_language, is_admin, created_at, updated_at FROM users ORDER BY created_at DESC
`

type ListUsersRow struct {
	ID                uuid.UUID      `json:"id"`
	Username          string         `json:"username"`
	Email             sql.NullString `json:"email"`
	PasswordHash      string         `json:"password_hash"`
	PreferredLanguage string         `json:"preferred_language"`
	IsAdmin           bool           `json:"is_admin"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.PreferredLanguage,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserActive = `-- name: UpdateUserActive :one
UPDATE users SET is_active = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, username, email, password_hash, preferred_language, is_admin, is_active, created_at, updated_at
`

type UpdateUserActiveParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive bool      `json:"is_active"`
}

type UpdateUserActiveRow struct {
	ID                uuid.UUID      `json:"id"`
	Username          string         `json:"username"`
	Email             sql.NullString `json:"email"`
	PasswordHash      string         `json:"password_hash"`
	PreferredLanguage string         `json:"preferred_language"`
	IsAdmin           bool           `json:"is_admin"`
	IsActive          bool           `json:"is_active"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

func (q *Queries) UpdateUserActive(ctx context.Context, arg UpdateUserActiveParams) (UpdateUserActiveRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserActive, arg.ID, arg.IsActive)
	var i UpdateUserActiveRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.PreferredLanguage,
		&i.IsAdmin,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE users SET email = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, username, email, password_hash, preferred_language, is_admin, is_active, created_at, updated_at
`

type UpdateUserEmailParams struct {
	ID    uuid.UUID      `json:"id"`
	Email sql.NullString `json:"email"`
}

type UpdateUserEmailRow struct {
	ID                uuid.UUID      `json:"id"`
	Username          string         `json:"username"`
	Email             sql.NullString `json:"email"`
	PasswordHash      string         `json:"password_hash"`
	PreferredLanguage string         `json:"preferred_language"`
	IsAdmin           bool           `json:"is_admin"`
	IsActive          bool           `json:"is_active"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (UpdateUserEmailRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserEmail, arg.ID, arg.Email)
	var i UpdateUserEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.PreferredLanguage,
		&i.IsAdmin,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserIsAdmin = `-- name: UpdateUserIsAdmin :one
UPDATE users SET is_admin = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, username, email, password_hash, preferred_language, is_admin, created_at, updated_at
`

type UpdateUserIsAdminParams struct {
	ID      uuid.UUID `json:"id"`
	IsAdmin bool      `json:"is_admin"`
}

type UpdateUserIsAdminRow struct {
	ID                uuid.UUID      `json:"id"`
	Username          string         `json:"username"`
	Email             sql.NullString `json:"email"`
	PasswordHash      string         `json:"password_hash"`
	PreferredLanguage string         `json:"preferred_language"`
	IsAdmin           bool           `json:"is_admin"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

func (q *Queries) UpdateUserIsAdmin(ctx context.Context, arg UpdateUserIsAdminParams) (UpdateUserIsAdminRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserIsAdmin, arg.ID, arg.IsAdmin)
	var i UpdateUserIsAdminRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.PreferredLanguage,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserPreferredLanguage = `-- name: UpdateUserPreferredLanguage :one
UPDATE users SET preferred_language = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, username, email, password_hash, preferred_language, is_admin, created_at, updated_at
`

type UpdateUserPreferredLanguageParams struct {
	ID                uuid.UUID `json:"id"`
	PreferredLanguage string    `json:"preferred_language"`
}

type UpdateUserPreferredLanguageRow struct {
	ID                uuid.UUID      `json:"id"`
	Username          string         `json:"username"`
	Email             sql.NullString `json:"email"`
	PasswordHash      string         `json:"password_hash"`
	PreferredLanguage string         `json:"preferred_language"`
	IsAdmin           bool           `json:"is_admin"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

func (q *Queries) UpdateUserPreferredLanguage(ctx context.Context, arg UpdateUserPreferredLanguageParams) (UpdateUserPreferredLanguageRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserPreferredLanguage, arg.ID, arg.PreferredLanguage)
	var i UpdateUserPreferredLanguageRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.PreferredLanguage,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
