// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: workspaces.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countWorkspacesByUser = `-- name: CountWorkspacesByUser :one
SELECT COUNT(*) FROM workspace_members WHERE user_id = $1
`

func (q *Queries) CountWorkspacesByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkspacesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (owner_id, name)
VALUES ($1, $2)
RETURNING id, owner_id, name, is_public, sort_order, created_at, updated_at
`

type CreateWorkspaceParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Name    string    `json:"name"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, createWorkspace, arg.OwnerID, arg.Name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.IsPublic,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces WHERE id = $1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspace, id)
	return err
}

const deleteWorkspaceMember = `-- name: DeleteWorkspaceMember :exec
DELETE FROM workspace_members 
WHERE workspace_id = $1 AND user_id = $2
`

type DeleteWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteWorkspaceMember(ctx context.Context, arg DeleteWorkspaceMemberParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspaceMember, arg.WorkspaceID, arg.UserID)
	return err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, owner_id, name, is_public, sort_order, created_at, updated_at FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.IsPublic,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceMember = `-- name: GetWorkspaceMember :one
SELECT id, workspace_id, user_id, level, created_at FROM workspace_members 
WHERE workspace_id = $1 AND user_id = $2
`

type GetWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Level,
		&i.CreatedAt,
	)
	return i, err
}

const listPublicWorkspaces = `-- name: ListPublicWorkspaces :many
SELECT id, owner_id, name, is_public, sort_order, created_at, updated_at FROM workspaces WHERE is_public = true ORDER BY updated_at DESC
`

func (q *Queries) ListPublicWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listPublicWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.IsPublic,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT wm.id, wm.workspace_id, wm.user_id, wm.level, wm.created_at, u.username
FROM workspace_members wm
JOIN users u ON wm.user_id = u.id
WHERE wm.workspace_id = $1
ORDER BY wm.created_at
`

type ListWorkspaceMembersRow struct {
	ID          uuid.UUID       `json:"id"`
	WorkspaceID uuid.UUID       `json:"workspace_id"`
	UserID      uuid.UUID       `json:"user_id"`
	Level       PermissionLevel `json:"level"`
	CreatedAt   time.Time       `json:"created_at"`
	Username    string          `json:"username"`
}

func (q *Queries) ListWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceMembersRow{}
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Level,
			&i.CreatedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesByMember = `-- name: ListWorkspacesByMember :many
SELECT w.id, w.owner_id, w.name, w.is_public, w.sort_order, w.created_at, w.updated_at FROM workspaces w
JOIN workspace_members wm ON w.id = wm.workspace_id
WHERE wm.user_id = $1
ORDER BY w.updated_at DESC
`

func (q *Queries) ListWorkspacesByMember(ctx context.Context, userID uuid.UUID) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspacesByMember, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.IsPublic,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesByOwner = `-- name: ListWorkspacesByOwner :many
SELECT id, owner_id, name, is_public, sort_order, created_at, updated_at FROM workspaces WHERE owner_id = $1 ORDER BY updated_at DESC
`

func (q *Queries) ListWorkspacesByOwner(ctx context.Context, ownerID uuid.UUID) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspacesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.IsPublic,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspaceName = `-- name: UpdateWorkspaceName :one
UPDATE workspaces
SET name = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, name, is_public, sort_order, created_at, updated_at
`

type UpdateWorkspaceNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateWorkspaceName(ctx context.Context, arg UpdateWorkspaceNameParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, updateWorkspaceName, arg.ID, arg.Name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.IsPublic,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkspacePublicStatus = `-- name: UpdateWorkspacePublicStatus :one
UPDATE workspaces
SET is_public = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, name, is_public, sort_order, created_at, updated_at
`

type UpdateWorkspacePublicStatusParams struct {
	ID       uuid.UUID `json:"id"`
	IsPublic bool      `json:"is_public"`
}

func (q *Queries) UpdateWorkspacePublicStatus(ctx context.Context, arg UpdateWorkspacePublicStatusParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, updateWorkspacePublicStatus, arg.ID, arg.IsPublic)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.IsPublic,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkspaceSortOrder = `-- name: UpdateWorkspaceSortOrder :exec
UPDATE workspaces SET sort_order = $2, updated_at = NOW() WHERE id = $1
`

type UpdateWorkspaceSortOrderParams struct {
	ID        uuid.UUID `json:"id"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) UpdateWorkspaceSortOrder(ctx context.Context, arg UpdateWorkspaceSortOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkspaceSortOrder, arg.ID, arg.SortOrder)
	return err
}

const upsertWorkspaceMember = `-- name: UpsertWorkspaceMember :one
INSERT INTO workspace_members (workspace_id, user_id, level)
VALUES ($1, $2, $3)
ON CONFLICT (workspace_id, user_id) 
DO UPDATE SET level = EXCLUDED.level
RETURNING id, workspace_id, user_id, level, created_at
`

type UpsertWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID       `json:"workspace_id"`
	UserID      uuid.UUID       `json:"user_id"`
	Level       PermissionLevel `json:"level"`
}

func (q *Queries) UpsertWorkspaceMember(ctx context.Context, arg UpsertWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRowContext(ctx, upsertWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.Level)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Level,
		&i.CreatedAt,
	)
	return i, err
}
